### ISSUE TITLE
debug DOL_SOL

### ISSUE THREAD

**Issue by judgelord** [judgelord/correspondence#1]
We have two sheets for DOL_SOL, the DOL_SOL.R script is written for the one called DOL_SOL (replicate), but should work with the other, which may be cleaner. 
We need to:
1. check sheets for completeness and have just one version
2. make sure DOL_SOL.R runs correctly 
3. make sure merge.R runs
4. inspect bad.names etc.

**Comment by judgelord** [comment]
~1500 bad.names.2 from misspellings and noMOCs. Needs manual checking.

**Comment by judgelord** [comment]
to break out multiple members, use something like this :
  mutate(FROM = FROM %>% str_split(";")) %>%
  unnest(members)

**Comment by Maggie-Nead** [comment]
Finished rewriting the code for splitting the observations for which there are multiple authors. Identified that ";" need to be split on as well but that still needs to be added to the code, I left a comment in the script as a reminder to myself.

**Comment by judgelord** [comment]
After this is done, assign #51

**Comment by Maggie-Nead** [comment]
Rewrote code to split first and last names with a comma. Split FROM on "and" and coded out all chamber assignments in FROM. The code for getLastFirstName still does not work.

**Comment by judgelord** [comment]
`getLastFirstName()` will only match Members of Congress. If you notice a pattern (e.g. a non-member who appears a lot), write a mutate ifelse line that adds a note to the ERROR column. 

If we investigate someone and find that they are not a member, we can also fill out the ERROR column in the raw data:
https://docs.google.com/spreadsheets/d/1ZCOVuyqDIVgzzukeoJ6IdjAzUWT7wzJOhPwvp8IbIZo/edit#gid=244208342

**Comment by Maggie-Nead** [comment]
Fixed some misspellings for N.A. first and last names and coded some error for state legislators. Code runs fine but middle initials sometimes combine with first names.

**Comment by judgelord** [comment]
Aside from some misspelled names that will show up in bad.names and should be corrected in nameMethods.R, this looks good.

**Comment by Maggie-Nead** [comment]
After other dataset were checked DOL_SOL showed up in worst_agencies. Some may not match because of NA chambers in the merge others are not matched because format for some of the names is Last_FirstInitial_Middle. I fixed some of the formats but more will need to be fixed as-well.

To do:
Fix more format problems
Run extractMemberName on full dataset

**Comment by Maggie-Nead** [comment]
Fixed name, format, and chamber typos
Coded Errors for non members
@judgelord Pellito, John is a community liaison for Congresswoman Louise Slaughter. I was not sure how we wanted to handle that so I just put it in NOTES. LUJAN, Michelle is not matched in the merge file and I am not sure why congress and chamber are both correct. Victor Snyder has another common name Rick #62 

After the merge ran for a 3rd time I pulled more unmatched observations than the previous time I'm not sure what happened and will need to investigate on Monday.

**Comment by Maggie-Nead** [comment]
Fixed problems with wrong chamber that caused more to not match in the merge file. Coded NOTES for observations that need FOIA
992/28088 most are observations that only say "others". There is a problem with Diaz-Balart, Lincoln in this script too #62. Script looks pretty good other than that.

FOIA List #76 
1. Representative Udall
Congress 110
ID: 618; 4075; 4280; 6304
LetterID: 482623; 518311; 520604; 540141
Dates: 2007-03-12; 2008-03-25; 2008-04-07; 2008-12-05

2. Senator Udall
Congress 111
ID: 8184; 8187
LetterID: 563310; 563313
Dates: 2009-06-18; 2009-06-18

**Comment by judgelord** [comment]
may need to use add_first where the chamber is missing "NA Murkowski"
