### ISSUE TITLE
debug FCC

### ISSUE THREAD

**Issue by fsabirinali** [judgelord/correspondence#105]
New data has been added for FCC and it will need some debugging (dates are in different format and some observations are missing IDs).

**Comment by fsabirinali** [comment]
ID column has been created.  Dates have been fixed as well (there was a dumb google sheet problem that was happening). Changed from getfirstLast to extractmembername.

**Comment by judgelord** [comment]
What remains to be done here?

**Comment by fsabirinali** [comment]
137 names still need to be corrected. All dates are matching.

**Comment by fsabirinali** [comment]
A few are missing first names and some are typos.  I am working on this.

**Comment by fsabirinali** [comment]
Typos are corrected, dates are correct.  I would consider this script to be working and clean.
