### ISSUE TITLE
debug DOT_FAA

### ISSUE THREAD

**Issue by judgelord** [judgelord/correspondence#109]

**Comment by fsabirinali** [comment]
460 names are unfound, however all dates have been added from PDF

**Comment by Maggie-Nead** [comment]
Rewrote string split in tidy
Cleaned FROM column of Jr's and extra commas that mess up format
Created LetterID and moved ID to after string split
Commented back in chamber variable and rewrote in tidy
Fixed some name typos
221 are still not matched in the dataset and 432 are not matched in merge out of 12465
 
To Do:
Some name formats look okay but still do not match these need to be investigated and I commented chamber back in but if more than one member wrote it and they are in different chambers this could cause problems. I will check this tomorrow.

**Comment by Maggie-Nead** [comment]
Fixed name and format typos
Commented out chamber
@judgelord the problem with "/n" 's in the console shows up in this dataset again. Some of the observations are in the wrong chamber in the FROM column, until I can fix this I have commented out chamber. Did we want to separate multiple members in the same observation? extractMemberName captures them but it seems a little messy. 210 names are not matched in the merge when chamber is commented out.

**Comment by judgelord** [comment]
Thanks, @Maggie-Nead; I'm not 100% clear on your question. 

We always want to split out members after making a `LetterID` column, then assign `ID`.

**Comment by Maggie-Nead** [comment]
Fixed name and format typos
Added ERRORs for non-members and agency staff
I also added semicolons to the google sheet for two observations to string split them in the dataset.

To do:
Observations that don't match seem to have extra spaces in the console and have to be re-coded by hand.

**Comment by judgelord** [comment]
Extra spaces should be taken out by nameMethods functions if possible. Is it possible to string replace some of them systematically? I'm happy to give it a shot if you have examples of strings you would like fixed.

**Comment by judgelord** [comment]
I made some edits to nameMethods that should do a better job of removing extra spaces. Let me know how if this solves the problems.

**Comment by Maggie-Nead** [comment]
Fixed some name and format typos and added errors for non members. I added code to trim whitespace and code to add ";" for observations with more than one member to string split on the ";".  @judgelord extractMemberName still does not capture Bono Mack, Mary. I can str_replace these to match on Bono, Mary but it seems like we should capture both of her last names. Some of the unmatched names in the merge have the wrong congress, there aren't very many so this week I'll fix those by hand in the code.

**Comment by Maggie-Nead** [comment]
@rochelle-snyder in DOT_FAA some of the observations say Udall, Mark E D/NM, can I assume this is supposed to be Udall, Tom as Mark Udall is from Colorado and Tom Udall is from New Mexico?

**Comment by Maggie-Nead** [comment]
Fixed name typos and added ";" by hand in the google sheet to split multiple members in the script. I also added code to match on state or congress and chamber for members with the same name, the code runs but doesn't do anything so I will continue to work on that this week.

**Comment by judgelord** [comment]
Bono Mack, Mary is a maiden name to be added to namecongress.R, right. Either way, tagging issue for #62

**Comment by rochelle-snyder** [comment]
@Maggie-Nead it depends on the observation; I think the ones in rows 3252 and 5118 are probably supposed to be Mark because he's writing with the other senator from CO. I'm not sure about the one in row 5007; I can't find any information about this letter online and it looks like Portman has worked with both Udalls before, so we may have to FOIA it.

**Comment by Maggie-Nead** [comment]
LUJAN GRISHAM, Michelle needs Lujan to be added as the maiden name and Grisham as last name so that both will match #9

**Comment by judgelord** [comment]
Thanks, Maggie; will you go ahead and add maiden names in nameCongress.R?

**Comment by Maggie-Nead** [comment]
Fixed some format and name typos and added errors for non members. I added some ";" to the google sheet by hand to split on them in the script. All of the names are matched in the script but there are still some unmatched names in the merge. Some of these need to have ";" added by hand to split them and some have odd spaces after the members name and before the state information that seems to prevent the merge script from a match.

**Comment by Maggie-Nead** [comment]
@rochelle-snyder in DOT_FAA there is a letter from a Carson, Aaron is it possible that this is Carson, Andre? The congresses and chamber match up.

**Comment by rochelle-snyder** [comment]
@Maggie-Nead I think so; it doesn't look like there were any other Aarons or Carsons in Congress at that time.

**Comment by Maggie-Nead** [comment]
I added ";" by hand for observations that did not split in the str_split(), and fixed name and format typos. There are 15 names still not matched in the merge script but they pull pattern and congress is correct so I can't figure out why they aren't matched.

**Comment by Maggie-Nead** [comment]
Fixed some state information that prevented matched names in the merge script.  The ones left may need FOIA because they could belong to two different members.

**Comment by Maggie-Nead** [comment]
@judgelord the clean agency script fills in wrong state information when there is more than one member with the same name. I can tell in the data set which member it is because there is a middle initial/middle name or state information but the clean agency script only looks at first and last name. For now, I just commented out the code that causes problems. I want to run the merge script before I delete anything.

**Comment by Maggie-Nead** [comment]
@judgelord there are a lot more unmatched names in the merge. It went from 14 observations in worst names to 145. I attempted to back track the problem in the commits but I haven't found it yet.
