### ISSUE TITLE
debug DOL_OWCP

### ISSUE THREAD

**Issue by fsabirinali** [judgelord/correspondence#110]

**Comment by fsabirinali** [comment]
All dates appear to be matched. 129 unfoundnames which I am currently beginning to correct.

**Comment by fsabirinali** [comment]
I will ned to finish up editing names and adding FOIA notes to the script.  Unfoundnames have gone down to 50.

**Comment by fsabirinali** [comment]
In the 115th congress there are only 544 observations, compared to all the other congress, where there are approximately 2352.  This might be something to check on in the future to see if we can add data/are we missing data?

**Comment by fsabirinali** [comment]
Names down to 27, I am trying to investigate ones with unknown members by finding letters/press releases online and have been adding them to the spreadsheets/correspondence folder.

**Comment by fsabirinali** [comment]
Finished debugging names.
FOIA Names #76 
1. Wittman and 17 others
Congress: 115
Letter (ID: 841997)
Date: 2017-10-04

2. Miller, George/ Polis/ Pocan/ Maloney & 15 Others
Congress: 113
Letters (ID: 742308)
Date: 2014-03-07

3. Murray, Patty/Sanders, Bernard/Scott, R. & 7 Other
Congress: 114
Letter (ID:790503 )
Date: 2015-11-02

4. Sessions, Jeff/ Alexander/ Voinovich & 12 Others
Congress: 110th
Letters (ID: 491252)
Date: 2007-06-05

5. Kennedy/Salazar/McGovern/Udall (Sens & Congs)
Congress: 109
Letters (ID: 482623)
Dates: 2007-03-12

6. Salazar, Ken/Udall/Salazar, J/Perlmutter, Ed (Congs) (not sure which Udall)
Congress: 110
Letter (ID: 520604)
Date: 2008-04-17

**Comment by fsabirinali** [comment]
All names appear to be matching and there appear to be no bad dates.  I would say that this script is clean.

**Comment by judgelord** [comment]
may need to add_first where there are only last names (e.g. Udall)
