### ISSUE TITLE
apply codebook to DHHS_IHS

### ISSUE THREAD

**Issue by judgelord** [judgelord/correspondence#138]
We should code a sample by hand and come up with coding rules to be applied using the script. Reply with any keywords or coding rules we should use.

**Comment by rochelle-snyder** [comment]
Finished a first pass at hand-coding. I coded requests on behalf of tribes as 3, but I'm not sure if that would be correct. 

There are also some interesting things we can do here with constituent type--many of the constituent letters are related to medical procedures, expenses, etc., but IHS also has a scholarship program for Native medical professionals, and there are a fair number letters about that.
