### ISSUE TITLE
apply codebook to DOL_OWCP

### ISSUE THREAD

**Issue by judgelord** [judgelord/correspondence#142]
We should code a sample by hand and come up with coding rules to be applied using the script. Reply with any keywords or coding rules we should use.

**Comment by rochelle-snyder** [comment]
Finished a first pass at hand-coding. The vast majority of it is personal service requests, so it was fairly straightforward. We can use keywords like "veteran," "disabled"/"disability"/"impairment," "hardship," "homeless," and maybe "black lung" to code for constituent type and class.

**Comment by judgelord** [comment]
Ok; let's add these to the constituent type sheet as we find them: https://docs.google.com/spreadsheets/d/1k8lVEJd2uUUzhPqKoLJOW4uDQ9RNRIyJKXx9RhKT6As/edit#gid=0

**Comment by judgelord** [comment]
@hkarnopp & @jderzay: Note how Rochelle identified keywords for this agency. We can apply these keywords in a few ways. First, we can just note them in the issue for applying the codebook as Rochelle did here. Second, we will eventually be writing R code to the effect of "if you see this word or phrase, then make it this type." Similarly, if letters are dealing with different types of constituents, we can add these to this [this sheet](https://docs.google.com/spreadsheets/d/1k8lVEJd2uUUzhPqKoLJOW4uDQ9RNRIyJKXx9RhKT6As/edit?usp=drive_web&ouid=101540876894576538638), which will auto-code observations matching those keywords.

**Comment by judgelord** [comment]
@rochelle-snyder are we ready to close this out?

**Comment by rochelle-snyder** [comment]
@judgelord Yes, I think so; I just wasn't sure if you wanted to leave these open until the agencies had been double-coded, so I hadn't been closing them. I can go back & close the issues for the agencies that I've coded.
