### ISSUE TITLE
apply codebook to DOT_PHMSA

### ISSUE THREAD

**Issue by judgelord** [judgelord/correspondence#144]

**Comment by hkarnopp** [comment]
Property = decision regarding easement, mandates, etc.

**Comment by hkarnopp** [comment]
Complaint = concern, usually from constituent or unspecified source; usually concerned about a general company or pipeline (no indication of a certain policy being violated or other specific information)

**Comment by hkarnopp** [comment]
Members of congress writing to agency concerning a pipeline spill I've been coding as 5; 2; 1. I'm interpreting the 5 as just general policy questions with disaster; information as the policy type. If it is a smaller spill and the member of congress is from the district where spill occured, they might be more likely to be advocating on behalf of constituents (1; 2; 5)

**Comment by hkarnopp** [comment]
Inspections of companies = enforcement, not decision;permit (not always a clear enforcement action though?)

**Comment by hkarnopp** [comment]
Audits = 5? (internal; OIG)

**Comment by hkarnopp** [comment]
***lots of unclear sources. Sometimes a company is mentioned, but some kind of action is being taken against the company and it's unclear if member of congress is advocating for/protecting a company, or if it's more of a 5 in that the company is violating a rule?

**Comment by hkarnopp** [comment]
***need to define disaster. Enbridge definitely is, and any spills that spur major changes in rules should be; but smaller spills like 173 shouldn't?

**Comment by judgelord** [comment]
Good questions. 
For now, let us define even small spills and unexpected events as disasters. 

Yes, oversight of an audit of a government agency is a type 5.

If one particular company is at issue, we just need to do our best code 2 or 5, possibly with high uncertainty if the member's position is unclear. You can try looking at open secrets campaign donations to see how the member aligns.

**Comment by hkarnopp** [comment]
There are a few cases where a company leads a petition for PHMSA to change a regulation, sometimes these relate to permits. There probably aren't enough that petition should be added to rulebook, so is it most related to rule? Also not sure if this is more of a 4 (applies to whole industry) or a 2 or 5?

**Comment by judgelord** [comment]
Good question. Typically a petition for rulemaking (petitions to change a regulation) is asking for a policy that would affect a whole industry, not just one company's permit, so it will be a 4 or a 5 depending on whether the member is pro or con. If they are commenting on a company's petition, it is probably more likely that they are supportive because the company is trying to get the agency to take up their issue. A member could be saying "don't do this" but I suspect those interventions come more after the agency starts the rulemaking process (most often when they publish a draft of the proposed rule change).

**Comment by hkarnopp** [comment]
For "legislation": does it have to be upcoming/in the future? Some cases where members of congress urging PHMSA to review, implement parts of past legislation

**Comment by hkarnopp** [comment]
Same thing with rule: does it have to be a proposal for a rule, or can it be broader legislation? (lots of vague cases like "inspections" "special permits" "pipeline issues" "continued use of tank cars" with no other specifications

**Comment by judgelord** [comment]
If legislation or a rule is mentioned, we should include those codes whether it is past or future. 

Inspections would probably fall under enforcement. 

Permits now have a category "decision;permit" -- perhaps we would also use this for "continued use of tank cars" since that seems to imply that the agency has some control over whether tank cars are used, either by permit or rule.

**Comment by hkarnopp** [comment]
Almost done, just going to go research pro/anti positions on cases dealing with bigger companies/disasters. Some things to note: 
- "Special permits" comes up a lot. If it's plural, I usually inferred a 4 since it was usually a case affecting an entire industry. It's possible this could be considered a 5 as well, since it also seems like a rule. If it said "special permit", I inferred it was a 2 (for a specific company/instance). 
- There are some petitions (for rulemaking) being led by companies. These cases can apply to 2, 4, and 5, but we might want to narrow down?
- With more experience, I realized that some cases might be 4s that I originally wasn't sure on. I think I went back and edited most of these, but might I have missed some.
- Interesting cases, comments, questions, and things that could be added to the codebook (complaints, property, etc.) are in the notes column. 
- Yellow highlighted first column means this case was confusing, ambiguous, or couldn't find enough information. Lots of these have 3 uncertainty, but I not all cases with 3 uncertainty are highlighted.

**Comment by hkarnopp** [comment]
DOT_PHMSA is ready to be looked at! I added pro/anti stances where I could in policy event and/or notes, this was easiest to find for Enbridge and TC Energy (Keystone Pipeline). For the larger companies, I put in the companies issue I tried to include information about committee membership or if the event was in the member's state when I couldn't find a clear pro/anti stance. One strange  case was Richard Lugar and the Rockies Express Pipeline, I couldn't find a ton of information on Lugar that would make sense but there were 4 or so cases with this company...might want to look at for donations?

**Comment by judgelord** [comment]
> ***need to define disaster. Enbridge definitely is, and any spills that spur major changes in rules should be; but smaller spills like 173 shouldn't?

This kind of thing should be added to the bottom of the codebook, in the section about tough cases.

**Comment by judgelord** [comment]
> Almost done, just going to go research pro/anti positions on cases dealing with bigger companies/disasters. Some things to note:
> 
> * "Special permits" comes up a lot. If it's plural, I usually inferred a 4 since it was usually a case affecting an entire industry. It's possible this could be considered a 5 as well, since it also seems like a rule. If it said "special permit", I inferred it was a 2 (for a specific company/instance).
> * There are some petitions (for rulemaking) being led by companies. These cases can apply to 2, 4, and 5, but we might want to narrow down?
> * With more experience, I realized that some cases might be 4s that I originally wasn't sure on. I think I went back and edited most of these, but might I have missed some.
> * Interesting cases, comments, questions, and things that could be added to the codebook (complaints, property, etc.) are in the notes column.
> * Yellow highlighted first column means this case was confusing, ambiguous, or couldn't find enough information. Lots of these have 3 uncertainty, but I not all cases with 3 uncertainty are highlighted.

1. One company may have multiple permits for a project, so this may simply be unclear--best to draw from other context clues if possible
2. Petitions for rulemaking by companies will be 4 most of the time since a rule will generally apply to the whole industry. 
3. Thanks for noting interesting cases! The note about Richard Lugar and the Rockies Express Pipeline is interesting and relevant to DOE_FERC #42
