### ISSUE TITLE
apply codebook to NARA

### ISSUE THREAD

**Issue by rochelle-snyder** [judgelord/correspondence#147]

**Comment by rochelle-snyder** [comment]
Just noticed that there are about 100 different observations all contained within the same row (5988 in the Google sheet). @judgelord should I put these into separate rows by hand?

**Comment by judgelord** [comment]
no; I'll just do this right now and paste it in. Good catch!

**Comment by judgelord** [comment]
done. added to the bottom of the sheet

**Comment by judgelord** [comment]
I see "agent orange" is noted in the constituent_type sheet. I think "military family" is super interesting if it is easy to detect. Feel free to close this out when you think it's done.

**Comment by rochelle-snyder** [comment]
There were lots of instances in NARA of constituents requesting family members' (mostly fathers, grandfathers, husbands) military records. I can go back and look at some of those to see what terms we might be able to use to identify them and add them to the constituent_type sheet for "military family."

**Comment by rochelle-snyder** [comment]
We can probably use "father," "grandfather," "husband," "brother," etc. to identify military families, although we'll have to be careful to make sure that these are all related to military records and not something else. I have added these terms to the constituent_type sheet. I'm not sure if we can make any strong assumptions about constituent class with these types of records requests, so I have left that blank for now.
