### ISSUE TITLE
apply codebook to Treasury_Fiscal

### ISSUE THREAD

**Issue by judgelord** [judgelord/correspondence#151]
@jderzay, if you can leave some notes about what you did, any difficult coding calls, I will take a look and close this issue. Thanks!

**Comment by jderzay** [comment]
I had no problems, and I believe this is done as well. Thanks!

**Comment by judgelord** [comment]
I see that this is coded using the constituent_types google sheet. This is the right way to do it. I just want to note it here. 

There are 6 types identified. 
-Debt
-Direct Deposit
-Check Claim
-Others
-EFT Reclamation
-Why Did I Get This Check

It is also very important to note that we cannot code these data for 2008, 2008, and parts of 2010 and 2011 because the SUBJECT field is missing.
