### ISSUE TITLE
apply codebook to DOJ_OSG

### ISSUE THREAD

**Issue by judgelord** [judgelord/correspondence#152]

**Comment by jderzay** [comment]
1.) Tagged all relevant cells with an Anti or Pro Company 
2.) Tagged all relevant cells as a certain group of constituents that were marked as a 1
3.) I have noticed an interesting trend of Pro or Anti Native American in my agency, as a lot has to do with cleanup of Native American reservations, land disputes, or debates on Native American health. So I began tagging Pro or Anti Native American as well. It is interesting to see a change from the Bush administration to the Obama Administration in this regard, I wonder if the Trump administration will shift from the Obama administration as well.

**Comment by jderzay** [comment]
I believe this is done as well, thanks!
