### ISSUE TITLE
DOC_MBDA missing dates

### ISSUE THREAD

**Issue by judgelord** [judgelord/correspondence#18]
very few dates can be extracted from the text, maybe some can be added to the sheet by hand?

**Comment by fsabirinali** [comment]
There is a table error in the script that should be fixed.

**Comment by judgelord** [comment]
Hmm, I'm not getting an error in the merge, @Maggie-Nead?

**Comment by judgelord** [comment]
Is this issue resolved? @Maggie-Nead @fsabirinali

**Comment by fsabirinali** [comment]
@judgelord  there is not longer a table error showing up when running the script.  There are 83 missing dates still, I added some by hand, but for the most part, the ones missing dates are really hard to figure out since there is nothing in the subject.

**Comment by judgelord** [comment]
Thanks @fsabirinali; we may need to get the dates from the original pdf. @rochelle-snyder, can you email the DOC_MBDA pdf to @fsabirinali

**Comment by fsabirinali** [comment]
Years have been added, however, even with the PDF, it is impossible to find the month and day for some of the observations.

**Comment by judgelord** [comment]
Thanks, @fsabirinali, as long as we are getting the right congress when we run the clean script, they should match.
