### ISSUE TITLE
clean script for DHS_USCIS

### ISSUE THREAD

**Issue by rochelle-snyder** [judgelord/correspondence#202]

**Comment by judgelord** [comment]
The script now runs and creates SUBJECT by combining a bunch of the columns on the right.

**Comment by judgelord** [comment]
This script works, but I am re-opening this issue because @rochelle-snyder is going to add some TYPE coding (see agencies/EPA.R)

**Comment by judgelord** [comment]
closing and moving TYPE coding to a new issue #206

**Comment by judgelord** [comment]
LetterID needs to be 6 digits (see other scripts)
