### ISSUE TITLE
clean script for DOL_ETA

### ISSUE THREAD

**Issue by rochelle-snyder** [judgelord/correspondence#203]

**Comment by judgelord** [comment]
@rochelle-snyder DOL_ETA is in the master data_list, but without a clean script, we get an error when the merge tries to run DOL_ETA.R and does not find it.

**Comment by JEMunson** [comment]
@judgelord @rochelle-snyder I amended the cleaning file, I think you have to test it to know if the changes helped or not.

**Comment by JEMunson** [comment]
I moved the file to the agencies folder so it should work now.
