### ISSUE TITLE
debug FDA

### ISSUE THREAD

**Issue by judgelord** [judgelord/correspondence#26]
2012-2018 data now on drive

waiting on 2007-2011? 
(RE: Sarah B. Kotler email)

May not require debugging, but should be checked.

**Comment by rochelle-snyder** [comment]
We have 2007-2011 but the PDFs have not been converted; I will try converting them this week.

**Comment by judgelord** [comment]
2007-2018 now on drive

**Comment by Maggie-Nead** [comment]
Rewrote split using tidy-verse, moved split to occur before code pulls out words that are not names in FROM. Coded for errors when non members were accounted for.

To Do:
Examine split for effectiveness

**Comment by Maggie-Nead** [comment]
Made edits to the google sheet to fix ";" splitting. Edited some name errors. 
Code looks good 215 out of 7,000 not matched most are not federal legislators some may be name errors. Code ran through Merge without errors.

**Comment by judgelord** [comment]
@Maggie-Nead FDA is not giving errors, but there must be a problem with names or dates because all observations are being dropped.

**Comment by judgelord** [comment]
The script looks good. 

@rochelle-snyder, we have 5-10x as many letters from 2013-2016 as we do from 2007-2011--is this right? Did FDA change something systematic?

**Comment by rochelle-snyder** [comment]
@judgelord Looking back at your e-mail conversations with the FDA FOIA rep, it looks like they had to split our request between 2012-present and 2007-2011, and to reduce the redaction load, you agreed to eliminate constituent correspondence from the 2007-2011 logs that we would receive. We can go back and FOIA those again at some point if you think we need to.

**Comment by rochelle-snyder** [comment]
Request for correspondence logs containing constituent correspondence for 2007-2011 submitted
