### ISSUE TITLE
reshape Treasury_Mint data

### ISSUE THREAD

**Issue by judgelord** [judgelord/correspondence#34]
Treasury_Mint data were delivered in a table spread across pages. It needs to be wrangled, perhaps by hand, so that observation rows align. This is complicated by redaction boxes that created extra rows, making alignment tricky. 

When that sheet tidy, make a new issue to make a clean script for it, then one to apply the codebook to it.

**Comment by rochelle-snyder** [comment]
Fixed and added to Drive
