### ISSUE TITLE
add new DHHS_CDC data to sheet

### ISSUE THREAD

**Issue by judgelord** [judgelord/correspondence#40]
This can be closed when CDC finishes it's rolling release. In the meantime, we need to add to the sheet each time CDC releases a new batch

**Comment by judgelord** [comment]
new files need to be merged with google sheet in DHHS_CDC merge interim releases.R

rename date recieved letter date as DATE etc

**Comment by rochelle-snyder** [comment]
Files on dropbox here: https://www.dropbox.com/home/comm/careers/FOIA%20data/To%20Code-Rich/HHS%20Centers%20for%20Disease%20Control%20and%20Prevention

**Comment by judgelord** [comment]
Added 2010-2013 to sheet. 
Merged using DHHS_CDC merge interim release.R
Still waiting on FOIA for 2007-2008, 2014-2015, and 2017-2018

**Comment by judgelord** [comment]
@rochelle-snyder, will you please notify me when we get the next release? Thanks!

**Comment by judgelord** [comment]
@rochelle-snyder Is this done, or should I merge the new release with the CDC merge script?

**Comment by rochelle-snyder** [comment]
@judgelord this is done; all of the new releases have been added to the sheet.

**Comment by judgelord** [comment]
Excellent.
