### ISSUE TITLE
clean script for FTC

### ISSUE THREAD

**Issue by rochelle-snyder** [judgelord/correspondence#53]

**Comment by rochelle-snyder** [comment]
Script already started. Need to pull "Rep" and "Sen" from FROM column, but some members who were House members and then senators only have Sen attached to their name for the entire time period, so the chamber will be wrong for some years if we use the title to determine the chamber. Also presidents (Pre) and vice presidents (Vic) in the data. @Maggie-Nead

**Comment by rochelle-snyder** [comment]
Needs brand-new script (script I started did not save) @Maggie-Nead

**Comment by Maggie-Nead** [comment]
Started script, coded for; loaded data, date format. Still need to remove chamber assignments in FROM and run extracting member names.

**Comment by judgelord** [comment]
note: all new clean scripts should be saved in the agencies folder.

**Comment by Maggie-Nead** [comment]
Script for FTC looks good, ran through the merge file without Error. There are 70 out of 12907 not matching most are misspelled names #62
