### ISSUE TITLE
debug Treasury_Fiscal

### ISSUE THREAD

**Issue by judgelord** [judgelord/correspondence#57]
We may be able to identify cosigned letters that came in at the same time. The ID column on the google sheet is incomplete, so we can't use that, but we do know that letter 4586 and 4587 are cosigned by Merkley and Wyden (received 10/8/14 at 10:35).

**Comment by judgelord** [comment]
We may need to try to split out multiple member names with str_split() %>% unnest() if there are a good number of multi-member letters -- otherwise, this code looks ok. We should check how well it works and debug.

**Comment by fsabirinali** [comment]
Runs with no errors, but drops 200 variables within d1 and data. Something to investigate in future.

**Comment by Maggie-Nead** [comment]
Deleted Unnecessary code
Switched Getfirstlast to extractmembername
Code should match more observations in merge

To Do:
investigate unmatched names that are not duplicates
run script through merge

**Comment by Maggie-Nead** [comment]
Fixed name and format typos
Most names that did not call patterns are now matched in dataset 

To Do:
Double check observations that call pattern but don't match for observations that are not duplicates
Run through merge

**Comment by fsabirinali** [comment]
All name errors have been fixed, unfoundnames should have 0 observations now.
