### ISSUE TITLE
Space between first name and middle initial being deleted and failing to match

### ISSUE THREAD

**Issue by Maggie-Nead** [judgelord/correspondence#63]
dataset sometimes deletes space between first name and middle initial making it so the name cannot match. The same problem has occurred in DOL_SOL, DHHS_CDC and FDA. This may be because the middle initial does not have a period directly after. For example in FDA 'Franken, AL S' becomes 'Franken, ALS'.

**Comment by judgelord** [comment]
This bug should be fixed. @Maggie-Nead, can you confirm?  

Related to #62
