### ISSUE TITLE
debug VA_CEM

### ISSUE THREAD

**Issue by judgelord** [judgelord/correspondence#68]
No names are extracted. 
There is chamber information, but no chamber variable created.

**Comment by fsabirinali** [comment]
Chamber variable added. Code works and has minimal errors.

**Comment by judgelord** [comment]
@rochelle-snyder, is it correct that we only have 23 observations, just for 2017 and a bit of 2018?

**Comment by rochelle-snyder** [comment]
@judgelord Yes - I asked the agency and they claimed that they did not keep logs prior to 2017.

**Comment by fsabirinali** [comment]
23 observations are found, no NA dates. Overall code works well and extractMemberName is being used for this script.

**Comment by fsabirinali** [comment]
VA_CEM has also been handcoded.  It is in the google sheet called VA_CEM Fatima. The VA_CEM google sheet itself has no handcoding done in it.
