### ISSUE TITLE
debug DOJ_ENRD

### ISSUE THREAD

**Issue by rochelle-snyder** [judgelord/correspondence#78]
Some names of additional co-signers contained in subjects; dates in MM-DD-YY format

**Comment by Maggie-Nead** [comment]
Started script
Created LetterID and agency variables
Formatted Date
String split for multiple members
Extracted Member names

To Do:
Note FOIA for "Davis" 
match last names with first names where there is no chamber

**Comment by judgelord** [comment]
Tagging #76: need to FOIA "Davis" letters from DOJ_ENRD and other agencies where we only have last names. @rochelle-snyder

**Comment by Maggie-Nead** [comment]
need to FOIA #76 
1. Davis
congress: 109 & 110
chamber: House
Letters 2 (LetterID: 2, 15)
Dates: 2006-12-19; 2007-03-12

2. Rogers
(Mike or Mike Dennis)
Congress: 112
Chamber: House
1 Letter (LetterID: 205)
Date: 2011-01-28

**Comment by Maggie-Nead** [comment]
Coded errors for non members
Coded notes for FOIA

444/1002 not matching. Most are extra rows left after string split some are from the 109th congress. Return to this dataset when extractmembername2 runs on all members.

To Do: 
Check for matched duplicates after split

**Comment by Maggie-Nead** [comment]
@judgelord Earl Benjamin Nelson does not have a chamber_last

**Comment by Maggie-Nead** [comment]
131/698 not matching many are committees but some are last names that wont match with first name #62

**Comment by Maggie-Nead** [comment]
need to FOIA #76 

Emanuel
(Rahm or Cleaver)
Congress 110
Date: 2007-04-05
1 Letter (LetterID: 16)
Chamber: House

**Comment by Maggie-Nead** [comment]
Most are matched however some such as Emanuel Cleaver and Senator Don Young should be matched and are not.

**Comment by rochelle-snyder** [comment]
Emanuel is Rahm - he was the Chair of the Democratic Caucus @Maggie-Nead

**Comment by rochelle-snyder** [comment]
I think the two Davises are both Thomas - he is mentioned in the subject for letter 15, which appears to be a follow-up to letter 2. And I think Rogers is Michael J. from Michigan; he is writing with another Michigan representative about the Bay Mills Indian Community, which is in Michigan. @Maggie-Nead

**Comment by judgelord** [comment]
Thanks, Everyone. @rochelle-snyder, if you are in a google sheet and see unclear names, it would be great to just fix them.

**Comment by rochelle-snyder** [comment]
Unclear names have all been fixed. Tag me if there are any problems with them.

**Comment by Maggie-Nead** [comment]
Commented out addFirst and instead pasted chamber into FROM when we only have last names and fixed some name and chamber typos

addFirst matched all but 53 in the dataset and extractMemberName matched less at 89 unmatched But this might be a good thing as addFirst might have over matched. I am going to investigate this tomorrow. 89/687 are currently matched after the merge, most observations do not contain members but a few do and need to be fixed in the script.

**Comment by Maggie-Nead** [comment]
@rochelle-snyder There is a letter about the 2010 oil spill on the Gulf, the LetterID is 161 and the date is 2010-05-26 and it only has last names. Most names can be matched just by the last name however I am wondering about Senator Nelson and Senator Udall. There is another letter that is almost identical to this one and appears to be written by the same people and includes first names the LetterID for that one is 157 with the same date. Can I assume these are the same people and the Letter is supposed to be from Bill Nelson and Mark Udall?

**Comment by judgelord** [comment]
We should circle back and close this out.

**Comment by Maggie-Nead** [comment]
Updated code to match on new patterns. Pasted chamber into from to match on chamber_last and deleted unneeded code.

**Comment by Maggie-Nead** [comment]
Fixed name and chamber typos. There are 70 unmatched non-observations after merge, all legislators should be matched. Cleaned up script, everything looks good now.
