### ISSUE TITLE
clean script for NWTRB

### ISSUE THREAD

**Issue by rochelle-snyder** [judgelord/correspondence#79]
Most of these are NOT members of Congress (they sent us a general correspondence log because they do not keep a separate congressional one, so we can just see how many names match)

**Comment by Maggie-Nead** [comment]
4/276 match, the rest seem to be non members

**Comment by Maggie-Nead** [comment]
Created ID and agency
formatted date, year and congress
extracted member name
Runs through the merge file without error 
4/276 match, other observations appear to not be members.
