### ISSUE TITLE
debug FDA 

### ISSUE THREAD

**Issue by rochelle-snyder** [judgelord/correspondence#97]
new data (constituent correspondence) added for 2007-2011

**Comment by fsabirinali** [comment]
Corrected dates in the script so that there are no negative congresses.

**Comment by Maggie-Nead** [comment]
Fixed string split. Removed [no org] in the FROM column to prevent extra observations. For certain congresses, blank strings are the most common observation. I assume that this is from the string split but I will investigate to make sure.

**Comment by Maggie-Nead** [comment]
Cleaned out unneeded code. FIxed name typos, cleaned FROM string, and added errors for nonmembers

**Comment by Maggie-Nead** [comment]
@judgelord There is a current problem with a double matched name in the scripts. Price, Tom is also matched to Rice, Tom. They are in the same chamber and in three of the same congresses. For now, I have recoded the string to match on middle name but we may want a long term solution as this probably happens in other scripts.

**Comment by judgelord** [comment]
#62
We should probably to add a space or $ to the last_comma_first pattern for Tom Rice: "( |$)Rice, Tom" 
Good catch!

**Comment by Maggie-Nead** [comment]
@rochelle-snyder Lance, Leonard (sort number 2355 in the google sheet) is listed in the FROM column twice for the same letter and I'm not sure if there is a reason for this.

**Comment by Maggie-Nead** [comment]
Fixed name and format typos and added common names to nameMethods. All unmatched names are non-members
